exclude: >
    (?x)^(
        build/.+|
        dist/.+|
        htmlcov/.+|
        my-module/build/.*|
        my-module/dist/.*|
        test_project/build/.*|
        test_project/dist/.*
    )$
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.4.0
    hooks:
    -   id: autopep8-wrapper
    -   id: check-added-large-files
    -   id: check-ast
    -   id: check-builtin-literals
    -   id: check-byte-order-marker
    -   id: check-case-conflict
    -   id: check-docstring-first
    -   id: check-json
    -   id: check-yaml
    -   id: debug-statements
    -   id: detect-private-key
    -   id: end-of-file-fixer
    -   id: name-tests-test
    -   id: sort-simple-yaml
    -   id: mixed-line-ending
    -   id: trailing-whitespace

    # -   id: flake8
    # -   id: detect-aws-credentials
    # -   id: forbid-new-submodules
    # -   id: requirements-txt-fixer
# -   repo: https://github.com/asottile/pyupgrade
#     rev: v1.2.0
#     hooks:
#     -   id: pyupgrade
-   repo: https://github.com/asottile/add-trailing-comma
    rev: v0.6.4
    hooks:
    -   id: add-trailing-comma
